# https://pnpm.io/settings

# Build Settings (https://pnpm.io/settings#build-settings)
verifyDepsBeforeRun: install
onlyBuiltDependencies:
  - esbuild

# https://pnpm.io/cli/run#shellemulator
shellEmulator: true
