name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      actions: read # Reaquired for `cancelled()`
      contents: read # Required for `actions/checkout`
      security-events: write # Required to upload SARIF file to code scanning alerts
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Enable Corepack
        # `corepack prepare --activate` is necessary as there is otherwise an error
        # Error: Cannot find matching keyid: {"signatures":[{"sig":"..."}...]...}
        #
        # @see {@link https://vercel.com/guides/corepack-errors-github-actions}
        # @see {@link https://github.com/nodejs/corepack/issues/612}
        run: |
          corepack enable
          corepack prepare --activate

      - name: Set up Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Lint code with ESLint
        id: eslint
        continue-on-error: true
        run: pnpm run lint --output-file results.sarif --format @microsoft/sarif

      - name: Upload SARIF file
        # https://github.com/jeremy-code/eslint-plugin-z/security/code-scanning
        if: ${{ cancelled() && steps.eslint.conclusion == 'failure' }}
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ steps.eslint.outputs.output-file }}
          category: eslint

      - name: Check code formatting with Prettier
        run: pnpm run format:check

      - name: Check types with TypeScript compiler
        run: pnpm run check-types

      - name: Run tests
        run: pnpm test

      - name: Build
        run: pnpm run build
