name: Release

on:
  push:
    branches: ["main"]
    paths-ignore: ["docs/**"]
  pull_request:
    types: [opened, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  version:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    permissions:
      attestations: write
      deployments: write
      packages: write
      id-token: write
      statuses: read
      checks: write
      actions: write
      contents: write
      pull-requests: write
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
        with:
          # Fetch all history for all branches and tags so that Changesets can
          # compare against the correct base branch
          fetch-depth: 0
          fetch-tags: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Enable Corepack
        run: |
          corepack enable
          corepack prepare --activate

      - name: Set up Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: pnpm
          cache-dependency-path: "pnpm-lock.yaml"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build

      - name: Create Release Pull Request or Publish to NPM
        id: changesets
        uses: changesets/action@v1
        continue-on-error: true
        with:
          publish: |
            pnpm publish --access public
            pnpm exec changeset tag
          version: pnpm exec changeset version
          commit: "chore(release): version packages"
          title: "chore(release): version packages"
          createGithubReleases: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Print Changesets output
        run: echo "${{ steps.changesets.outputs.published }} ${{ steps.changesets.outputs.publishedPackages }} ${{ steps.changesets.outputs.hasChangesets }} ${{ steps.changesets.outputs.pullRequestNumber }}"

      - name: Push Git tag after publishing
        # https://github.com/changesets/changesets/blob/main/docs/command-line-options.md#git-tags
        if: steps.changesets.outputs.published == 'true'
        run: git push --follow-tags
