name: Release

on:
  push:
    branches: ["main"]
    paths-ignore: ["docs/**"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: write # Required to create release
      pull-requests: write # Required to create PR
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
        with:
          # Fetch all history for all branches and tags so that Changesets can
          # compare against the correct base branch
          fetch-depth: 0

      - name: Enable Corepack
        run: |
          corepack enable
          corepack prepare --activate

      - name: Set up Node.js environment
        uses: actions/setup-node@v4
        id: setup-node
        with:
          node-version-file: .node-version
          cache: pnpm
          registry-url: https://registry.npmjs.org
          always-auth: true

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build

      - name: Create pull request for version bump and publish to npm
        uses: changesets/action@v1
        with:
          publish: pnpm exec changeset publish
          version: pnpm exec changeset version
          commit: "chore(release): version packages"
          title: "chore(release): version packages"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
